export default {

  groups: [{
    nummer: 'A',
    teams: [{
      name: 'Frankreich',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Rumänien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Albanien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Schweiz',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }]
  }, {
    nummer: 'B',
    teams: [{
      name: 'England',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Russland',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Wales',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Slowakei',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }]
  }, {
    nummer: 'C',
    teams: [{
      name: 'Deutschland',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Ukraine',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Polen',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Nordirland',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }]
  }, {
    nummer: 'D',
    teams: [{
      name: 'Spanien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Tschechien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Türkei',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Kroatien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }]
  }, {
    nummer: 'E',
    teams: [{
      name: 'Belgien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Italien',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Irland',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Schweden',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }]
  }, {
    nummer: 'F',
    teams: [{
      name: 'Portugal',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Island',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Österreich',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }, {
      name: 'Ungarn',
      punkte: 0,
      torePlus: 0,
      toreMinus: 0
    }]
  }
  ],

  users: [{
    name: 'Angelika'
  }, {
    name: 'Christian'
  }
  ]
};
